### ISSUE TITLE
Jason - thoughts

### ISSUE THREAD

**Issue by jason-amplified** [sumitii/tigersoup#14]
I think this is where this goes, listed in order of priortiy

**Quarto Font:**
I’m not seeing the font “Quarto” being used as our headline font choice. It looks to me like it’s various weights of Chronicle Text. Everything on the main splash page should be Quarto. 

Almost all “headline” or “section titles” (the fonts in green) should be Quarto. 

**Ringside Font:**
The sidebar nav should be ringside. Ringside is used sporadically throughout, it’s intended to be the meta font choice. The UX wireframes calls that out. 

**Navigation:**
The top bar navigation (Tiger Soup is a marketing communications company) and Enjoy your [weekday] should always stick to the top. And the side bar nav should be aligned to the middle of the page. 

**Page Length:**
The endless scroll is confusing to me. Can we break it up so there are distinct pages?

**Carousel:**
- Is there a way to not make the whole thing slide from left to right? If it all has to be the same, i think a fade would be nicer. It’s just a lot of movement. Also is it on a timer? It doesn’t scroll unless I click the dots at the bottom.

- Can we force the line breaks of “Tigersoup is a marketing communications company” and the “If you want tiger soup, you have to catch a tiger.” To be on two lines how it is in the wireframes?” Right now it’s breaking the lines up in a janky way.

- The Transition to “our approach” when you scroll down needs to be finessed. When we initially scroll down the first part of the copy is almost scrolled off screen. And the artwork should still be there so it lands nicely on the main navigation. If this is too difficult to implement, we should rethink this effect.

**Comment by sumitii** [comment]
Hi,

So far I have done the following:

- updated fonts
- carousel has a fade animation instead of slide transition
- set the carousel to be on a timer (2000ms per slide)

**Comment by sumitii** [comment]
Monday updates:

- Pages are now individual instead of an infinite scroll
- Carousel is hidden for launch
- Updated functionality of mobile navigation
